name: "Save PR number to file"
description: "Save PR number to a text file and upload the artifact"
inputs:
  artifact_name:
    description: "Name of the output artifact"
    default: "pr_number"
runs:
  using: "composite"
  steps:
  - name: Save PR number
    env:
      PR_NUMBER: ${{ github.event.number }}
    shell: bash
    run: |
      mkdir -p ./pr
      echo $PR_NUMBER > ./pr/pr_number.txt
  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      path: pr/
      name: ${{ inputs.artifact_name }}
