name: "Save PR number to file"
description: "Save PR number to a text file and upload the artifact"
inputs:
  artifact_name:
    description: "Name of the output artifact"
    default: "pr_number"
runs:
  using: "composite"
  steps:
    - name: Save PR number
      shell: bash
      run: |
        # Save PR number to text file
        echo ${{ github.event.issue.number }} > pr_number
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./pr_number
        name: ${{ inputs.artifact_name }}
