name: "Save PR number to file"
description: "Save PR number to a text file and upload the artifact"
inputs:
  artifact_name:
    description: "Name of the output artifact"
    default: "pr_number"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: jwalton/gh-find-current-pr@master
    id: findPr
    with:
      state: open
  - name: Save PR number
    if: success() && steps.findPr.outputs.number
    shell: bash
    run: |
      # Save PR number to text file
      echo ${PR} > pr_number
    env:
      PR: ${{ steps.findPr.outputs.pr }}
  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      path: ./pr_number
      name: ${{ inputs.artifact_name }}
