name: "Save artifact data to file"
description: "Save PR number and Artifact link to a text file and upload as artifact"
inputs:
  artifact_link:
    description: "Artifact link"
    required: true
  output_name:
    description: "Name of the output artifact"
    required: false
    default: "appsharingspace"
runs:
  using: "composite"
  steps:
  - name: Save PR number and Artifact link
    env:
      PR_NUMBER: ${{ github.event.number }}
    shell: bash
    run: |
      mkdir -p ./data
      echo $PR_NUMBER > ./data/pr_number.txt
      echo ${{ inputs.artifact_link }} > ./data/artifact_link.txt
  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      path: data/
      name: ${{ inputs.output_name }}
